Add missing <cmath> header and remove <string.h> header
The following errors are reported by GCC (6.0.0, r233941):

    Utilities/StorageFactory/src/StatisticsSenderService.cc:82:191: error: 'sqrt' was not declared in this scope
    Utilities/StorageFactory/src/StatisticsSenderService.cc:90:191: error: 'sqrt' was not declared in this scope

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>